#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

STAGED_FILES=$(git diff --name-only --cached --diff-filter=ACM)
if [ -n "$STAGED_FILES" ]; then
  npm run format:fix -- $STAGED_FILES
  git add $STAGED_FILES
  npm run lint -- $STAGED_FILES
fi
